[SCSE-58] Footer Map Component with Footer Content
ntuscse/website pull request #17
Opened 2022-11-09 15:24 UTC by venusnmj

- for 'content.button' type of footer content, edit 'href', 'ctaTitle', 'btnText'
- for 'content.type' type of footer content, edit 'alerts' array

[SCSE-58]

2022-11-10 07:08 UTC, xJQx requested changes

2022-11-10 07:08 UTC, xJQx commented on packages/ui/components/footer/Update.tsx
> +export const Update = ({ title, description } : UpdateProps) => {
Is there a better way to name this component other than "Update"? This name might be abit confusing 🤔

2022-11-10 07:08 UTC, xJQx commented on packages/ui/components/footer/ContentButton.tsx
> +export const ContentButton = ( { href, title, label } : ContentButtonProps) => {
name as 'FooterContentButton"?

2022-11-10 07:08 UTC, xJQx commented on packages/ui/components/footer/ContentText.tsx
> +export const ContentText = ( { alerts } : ContentTextProps) => {
name as 'FooterContentText"?

2022-11-10 16:59 UTC, venusnmj commented
work in progress to create separate storybook components for footer content button and footer content text components

2022-11-11 14:41 UTC, xJQx requested changes

2022-11-12 13:12 UTC, xJQx approved these changes
lgtm 🚀

2022-11-12 13:13 UTC, merged