[SCSE-148] Added feature for Blog CMS upload image to AWS S3
ntuscse/website pull request #52
Opened 2023-02-03 15:02 UTC by ztjhz

2023-02-24 14:34 UTC, RealDyllon requested changes

2023-02-24 14:34 UTC, RealDyllon commented on apps/cms/src/payload.config.ts
> +import { s3Adapter } from '@payloadcms/plugin-cloud-storage/s3';
can we alias this import to `createS3Adapter` ? So that it doesn't conflict with `s3adapted` (below)

2023-02-24 14:34 UTC, RealDyllon commented on apps/cms/src/payload.config.ts
> +const adapter = s3Adapter({
can we rename this to `s3Adapter`

2023-02-27 06:25 UTC, RealDyllon commented
Hey @ztjhz there's a conflict in this PR. Could you help to resolve?

2023-02-27 07:32 UTC, ztjhz commented
> Hey @ztjhz there's a conflict in this PR. Could you help to resolve?

Fixed!

2023-02-27 07:33 UTC, RealDyllon approved these changes
LGTM 🚀

2023-02-27 07:36 UTC, merged