Task/scse 149
ntuscse/website pull request #57
Opened 2023-02-12 15:20 UTC by keykey117

[SCSE-149] Added blogs.json and python script to import blogs onto payload.

2023-02-24 14:14 UTC, RealDyllon requested changes

2023-02-24 14:14 UTC, RealDyllon commented on apps/cms/src/import/import_script.py
> +        'Cookie': 'payload-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtleXlld0BnbWFpbC5jb20iLCJpZCI6IjYzZTNiMDVlOGVlNjU5MTgwMDE4MWIxOSIsImNvbGxlY3Rpb24iOiJ1c2VycyIsImlhdCI6MTY3NjIwNzc0M
Let's make this an env var

2023-02-24 14:15 UTC, RealDyllon requested changes

2023-02-24 14:15 UTC, RealDyllon commented on apps/cms/src/import/import_script.py
> +url = "http://localhost:3000/api/posts"
can make this an env var file.

2023-02-24 14:15 UTC, RealDyllon commented on apps/cms/src/import/import_script.py
> +        "author": "63e3b05e8ee6591800181b19",
make this an env var too

2023-02-24 14:35 UTC, RealDyllon commented
@keykey117 can rename this PR?

2023-02-28 08:18 UTC, RealDyllon submitted a review, later dismissed
LGTM

2023-03-11 06:38 UTC, jamiegoh requested changes
can you add a readme about the required dependencies + .env vars needed like Blog_URL

2023-03-11 12:44 UTC, jamiegoh requested changes
can you combine the text in .env.example and requirements into the readme

2023-03-12 15:59 UTC, jamiegoh approved these changes
LGTM

2023-03-12 17:09 UTC, merged